const allQuestionsData = [
{ question: "Kompyuter tizimining asosiy tarkibiy qismi (Hardware) nima?", options: ["Protsessor (CPU), Operativ xotira (RAM), Onaplata va Qattiq disk (HDD/SSD).", "Operatsion tizim (OS) hamda barcha turdagi amaliy va tizim dasturlari.", "Foydalanuvchi interfeysining grafik qismi, ya'ni tizimning vizual ko'rinishi.", "Barcha turdagi viruslarga qarshi kurashish uchun mo'ljallangan antivirus dasturi."], correctText: "Protsessor (CPU), Operativ xotira (RAM), Onaplata va Qattiq disk (HDD/SSD)." },
            { question: "Fanining asosiy maqsadi nima?", options: ["Tizimlar samaradorligini ta'minlash, sozlash, nosozliklarni aniqlash hamda bartaraf etish usullarini o'rgatish.", "Faqat kompyuterning ichki qurilmalarini yig'ish, ulash va ularga elektr quvvati yetkazish jarayonlarini o'rgatish.", "Faqat yuqori darajadagi dasturlash tillarini o'rganish va ularda murakkab dasturlar yaratishni o'rgatish.", "Faqat barcha turdagi tarmoq kabellarini to'g'ri ulash va tarmoq topologiyasini yaratishni o'rgatish."], correctText: "Tizimlar samaradorligini ta'minlash, sozlash, nosozliklarni aniqlash hamda bartaraf etish usullarini o'rgatish." },
            { question: "Kompyuter tizimining dasturiy tarkibiy qismi (Software) nima?", options: ["Operatsion tizim, Drayverlar, Amaliy dasturlar.", "Monitor, Klaviatura, Sichqoncha kabi ma'lumot kiritish-chiqarish qurilmalari.", "Quvvat manbai va kompyuter Korpusi (case) kabi tashqi va ichki fizik qismlar.", "Tarmoq kartasi (NIC) va Router (yo'riqchi) kabi tarmoq ulanish qurilmalari."], correctText: "Operatsion tizim, Drayverlar, Amaliy dasturlar." },
            { question: "Kompyuter tizimlarining asosiy vazifalaridan biri nima?", options: ["Axborotni qayta ishlash, saqlash, uzatish va qabul qilishni ta'minlash.", "Faqat murakkab grafik dizayndagi matnli hujjatlarni yaratish va ularni tahrirlash kabi jarayonlar.", "Faqat yuqori talabchan video o'yinlar o'ynash uchun qulay va tezkor sharoit yaratish.", "Faqat quvvat manbaini ulash, uzish va uning ish rejimlarini nazorat qilish."], correctText: "Axborotni qayta ishlash, saqlash, uzatish va qabul qilishni ta'minlash." },
            { question: "Texnik xizmat ko‘rsatish tushunchasi nimani anglatadi?", options: ["Kompyuterning apparat qismini tekshirish, ta'mirlash, profilaktika va modernizatsiya qilish.", "Faqatgina kompyuterga o'rnatilgan barcha amaliy dasturlarni har hafta yangilab borish jarayoni.", "Faqat yangi operatsion tizimni o'rnatish va uning konfiguratsiyasini qayta sozlash.", "Faqat foydalanuvchi parolini o'zgartirish va xavfsizlik sozlamalarini qayta tiklash."], correctText: "Kompyuterning apparat qismini tekshirish, ta'mirlash, profilaktika va modernizatsiya qilish." },
            { question: "Dasturiy xizmat ko‘rsatish nima?", options: ["OT, drayverlar, amaliy dasturlarni sozlash, yangilash, nosozliklarni dasturiy yo'l bilan bartaraf etish.", "Protsessor sovutish tizimiga termopasta sursh va ularning holatini tekshirish.", "Kompyuterning asosiy elektr quvvat manbaini almashtirish yoki ta'mirlash.", "Kompyuter korpusini ochish va ichidagi barcha komponentlarni changdan tozalash."], correctText: "OT, drayverlar, amaliy dasturlarni sozlash, yangilash, nosozliklarni dasturiy yo'l bilan bartaraf etish." },
            { question: "Kompyuterga texnik xizmat ko'rsatishning profilaktik chorasi nima?", options: ["Kompyuterni changdan tozalash va sovutish tizimini muntazam tekshirish.", "Operatsion tizimni har oyda tizimli ravishda qayta o'rnatish.", "Virus bilan zararlangan deb gumon qilingan barcha fayllarni o'chirish.", "Internet tezligini dasturiy usullar yordamida maksimal darajada oshirish."], correctText: "Kompyuterni changdan tozalash va sovutish tizimini muntazam tekshirish." },
            { question: "Qaysi qurilma kompyuterning \"miyasi\" deb ataladi va barcha hisoblash amallarini bajaradi?", options: ["CPU (Central Processing Unit) - Markaziy Protsessor.", "RAM (Random Access Memory) - Operativ xotira.", "HDD (Hard Disk Drive) - Qattiq disk, ma'lumotlar saqlash qurilmasi.", "GPU (Graphics Processing Unit) - Grafik Protsessor."], correctText: "CPU (Central Processing Unit) - Markaziy Protsessor." },
            { question: "Qisqa muddatli ma'lumotlarni saqlash va protsessorga tezkor kirishni ta'minlaydigan xotira turi qaysi?", options: ["Operativ xotira (RAM).", "Qattiq disk (HDD) yoki SSD kabi doimiy saqlash qurilmasi.", "Doimiy xotira (ROM) yoki tizimning asosiy saqlash joyi.", "Flesh xotira (Flash Drive) kabi ko'chma xotira qurilmasi."], correctText: "Operativ xotira (RAM)." },
            { question: "Kompyuter tizimiga texnik xizmat ko'rsatishning asosiy vazifasi nima?", options: ["Tizimning uzoq muddatli va uzluksiz ishlashini ta'minlash.", "Faqat yangi va yuqori talabchan o'yinlarni tez-tez o'rnatish.", "Faqat kompyuterning tashqi ko'rinishini estetik jihatdan yaxshilash.", "Faqat dasturlash qobiliyatini turli xil usullar bilan oshirish."], correctText: "Tizimning uzoq muddatli va uzluksiz ishlashini ta'minlash." },
            { question: "Kompyuterdagi axborotlar saqlanadigan doimiy xotira qurilmasi qaysi?", options: ["Qattiq disk (HDD/SSD).", "Operativ xotira (RAM) kabi vaqtinchalik saqlash joyi.", "Protsessor kesh xotirasi (L1, L2, L3) kabi juda tezkor xotira.", "Video xotira (VRAM) kabi faqat grafik ma'lumotlar uchun mo'ljallangan xotira."], correctText: "Qattiq disk (HDD/SSD)." },
            { question: "Drayver nima uchun kerak?", options: ["Operatsion tizim va apparat qurilmalari o'rtasidagi aloqani ta'minlash uchun.", "Kompyuter korpusini tashqi shikastlanishdan ishonchli himoya qilish uchun qism.", "Internetga simsiz ulanishni ta'minlash uchun modem yoki router qurilmasi.", "Ekranda tasvir yoki rasm chiqarish uchun videokarta qurilmasi."], correctText: "Operatsion tizim va apparat qurilmalari o'rtasidagi aloqani ta'minlash uchun." },
            { question: "Texnik xizmat ko'rsatishda nosozlikni bartaraf etish bosqichidan avval nima qilish zarur?", options: ["Nosozlikning sababini aniqlash (diagnostika) jarayonini o'tkazish.", "Darhol eski qurilma o'rniga yangi kompyuter sotib olish.", "Kompyuterdagi barcha o'rnatilgan dasturlarni o'chirish.", "Kompyuterni bir necha marotaba qayta yoqish."], correctText: "Nosozlikning sababini aniqlash (diagnostika) jarayonini o'tkazish." },
            { question: "Kompyuterning ishlashini sekinlashtiradigan eng keng tarqalgan dasturiy muammo nima?", options: ["Zararkunanda dasturlar (viruslar) va keraksiz fayllarning ko'payishi.", "Monitorning yorqinligi yoki kontrast darajasi past bo'lishi.", "Klaviatura tugmachalarining tiqilib qolishi va ularning sust ishlashi.", "Kompyuterning Korpusi fizik jihatdan juda kichik o'lchamda bo'lishi."], correctText: "Zararkunanda dasturlar (viruslar) va keraksiz fayllarning ko'payishi." },
            { question: "Texnik xizmat ko'rsatishda kabel menejmenti (cable management) nima uchun muhim?", options: ["Sovutish tizimi samaradorligini oshirish va ichki qismlarga kirishni osonlashtirish.", "Kompyuterni baland ovozda ishlashi va video montaj jarayonini tezlashtirish uchun kerak.", "Dasturlarni tezroq yuklash jarayonini amalga oshirish uchun vosita.", "Internetga ulanish tezligini sun'iy ravishda cheklash uchun."], correctText: "Sovutish tizimi samaradorligini oshirish va ichki qismlarga kirishni osonlashtirish." },
            { question: "Onaplata (Motherboard) ning asosiy vazifasi nima?", options: ["Barcha apparat qismlarini birlashtirish va ular o'rtasida ma'lumot almashinuvini ta'minlash.", "Kompyuterga tashqi quvvat berish jarayonini boshqarish va operatsion tizimni doimiy ravishda saqlash.", "Faqat operatsion tizimni doimiy ravishda saqlash.", "Faqat grafikani qayta ishlash va tasvirni ekranga uzatish."], correctText: "Barcha apparat qismlarini birlashtirish va ular o'rtasida ma'lumot almashinuvini ta'minlash." },
            { question: "BIOS (Basic Input/Output System) nimaga xizmat qiladi?", options: ["Kompyuterni ishga tushirish (boot) jarayonini boshqarish va apparat qismlarini tekshirish.", "Foydalanuvchiga matn yozish va hujjatlar yaratish imkonini berish.", "Internet orqali katta hajmli ma'lumot uzatish.", "Kompyuter ekranida yuqori aniqlikdagi rasm chiqarish, montaj jarayonini tezlashtirish uchun."], correctText: "Kompyuterni ishga tushirish (boot) jarayonini boshqarish va apparat qismlarini tekshirish." },
            { question: "Texnik xizmat ko'rsatishda termopastani almashtirish qaysi qurilma uchun muhim?", options: ["Protsessor (CPU) va/yoki Grafik karta (GPU).", "Qattiq disk (HDD) kabi ma'lumot saqlash qurilmasi.", "Operativ xotira (RAM) modullari.", "Quvvat manbai (PSU) qurilmasining ichki qismlari."], correctText: "Protsessor (CPU) va/yoki Grafik karta (GPU)." },
            { question: "Dasturiy xizmat ko'rsatishda registrdagi xatolarni tuzatish nima uchun muhim?", options: ["Operatsion tizimning ishlashini tezlashtirish va barqarorligini oshirish uchun.", "Monitorning o'lchamini kattalashtirish yoki kichraytirish uchun.", "Tarmoq parolida xavfsizlikni maksimal darajada kuchaytirish uchun.", "Klaviatura tilini avtomatik ravishda almashtirish uchun."], correctText: "Operatsion tizimning ishlashini tezlashtirish va barqarorligini oshirish uchun." },
            { question: "Kompyuter tizimi \"Kiritish qurilmalari\" ga nimalar kiradi?", options: ["Klaviatura, Sichqoncha, Skaner, Mikrofon.", "Monitor, Printer, Proyektor kabi ma'lumotlarni chiqarish qurilmalari.", "Protsessor, Operativ xotira kabi ma'lumotlarni qayta ishlash qurilmalari.", "Onaplata, Quvvat manbai kabi asosiy qismlar."], correctText: "Klaviatura, Sichqoncha, Skaner, Mikrofon." },
            { question: "Kompyuter tizimi \"Chiqarish qurilmalari\" ga nimalar kiradi?", options: ["Monitor, Printer, Proyektor.", "Klaviatura, Sichqoncha, Veb-kamera kabi ma'lumotlarni kiritish qurilmalari.", "Qattiq disk, Flesh xotira kabi ma'lumotlarni saqlash qurilmalari.", "Tarmoq kartasi, Modem kabi tarmoqqa ulanish qurilmalari."], correctText: "Monitor, Printer, Proyektor." },
            { question: "Qaysi xizmat ko'rsatish turi kompyuter xavfsizligini ta'minlashga qaratilgan?", options: ["Antivirus va Firewall dasturlarini sozlash, yangilash.", "Protsessorni yangi va tezkor turiga almashtirish.", "Monitor o'lchamini o'zgartirish va displey yorqinligini sozlash.", "Klaviatura va boshqa kiritish qurilmalarini profilaktik tekshiruvdan o‘tkazish."], correctText: "Antivirus va Firewall dasturlarini sozlash, yangilash." },
            { question: "Texnik xizmat ko'rsatishda \"upgrade\" (yangilash) deganda nimani tushunasiz?", options: ["Eskirgan apparat qismlarini yanada samaraliroq yangi qismlar bilan almashtirish.", "Operatsion tizimni kompyuterdan butunlay o'chirish.", "Tarmoq kabelini uzish va kompyuter nomini o'zgartirish kabi jarayonlar.", "Kompyuter nomini o'zgartirish."], correctText: "Eskirgan apparat qismlarini yanada samaraliroq yangi qismlar bilan almashtirish." },
            { question: "Fan vazifalaridan biri bo'lgan dokumentatsiya (hujjatlashtirish) nima uchun kerak?", options: ["Bajarilgan ishlar, konfiguratsiya o'zgarishlari va nosozliklarni bartaraf etish jarayonlarini qayd etib borish uchun.", "Kompyuterning sotish narxini to'g'ri belgilash va foydalanuvchini turli xil qo'shimcha ma'lumotlar bilan ta’minlash.", "Faqat foydalanuvchini turli xil qo'shimcha ma'lumotlar bilan chalg'itish uchun.", "Faqat internetda e'lon qilish uchun talab qilinadi."], correctText: "Bajarilgan ishlar, konfiguratsiya o'zgarishlari va nosozliklarni bartaraf etish jarayonlarini qayd etib borish uchun." },
            { question: "Texnik xizmat ko'rsatishda multimetr (o'lchash asbobi) qaysi qurilmalarni tekshirish uchun ishlatiladi?", options: ["Quvvat manbai va kabellardagi o'tkazuvchanlikni tekshirish uchun.", "Operatsion tizimning barcha fayllarini tekshirish uchun vosita.", "Kompyuterdagi turli xil viruslarni aniqlash uchun dastur.", "Dasturlarning ishlash tezligini o'lchash va kuchaytirish uchun dasturiy vosita."], correctText: "Quvvat manbai va kabellardagi o'tkazuvchanlikni tekshirish uchun." },
            { question: "CPU ning asosiy vazifasi nima?", options: ["Dasturlarning ko'rsatmalarini bajarish va hisoblash amallarini amalga oshirish.", "Ma'lumotlarni doimiy saqlash va tartiblash hamda grafik tasvirni ekranga yuqori sifatda chiqarish.", "Tarmoqqa uzluksiz ulanishni ta'minlash.", "Grafik tasvirni ekranga yuqori sifatda chiqarish."], correctText: "Dasturlarning ko'rsatmalarini bajarish va hisoblash amallarini amalga oshirish." },
            { question: "CPU ning asosiy tarkibiy qismlari qaysilar?", options: ["Arifmetik-mantiqiy qurilma (ALU) va Boshqaruv qurilmasi (CU).", "Monitor va klaviatura kabi ma'lumot kiritish-chiqarish qurilmalari.", "Qattiq disk va USB port kabi tashqi ulanish portlari.", "Router (yo'riqchi) va modem kabi tarmoq qurilmalari."], correctText: "Arifmetik-mantiqiy qurilma (ALU) va Boshqaruv qurilmasi (CU)." },
            { question: "Operativ xotira (RAM) va Kesh xotira o'rtasidagi asosiy farq nima?", options: ["Kesh protsessorga RAMga qaraganda tezroq va yaqinroq joylashgan, hajmi kichikroq.", "RAM ma'lumotlarni doimiy saqlaydi, Kesh xotira esa ma'lumotlarni uzoq muddatga saqlamaydi.", "Kesh xotira faqat tarmoq ma'lumotlari uchun maxsus ishlatiladigan xotira turi.", "RAM faqat ma'lumot yozish uchun, Kesh xotira faqat ma'lumot o'qish uchun."], correctText: "Kesh protsessorga RAMga qaraganda tezroq va yaqinroq joylashgan, hajmi kichikroq." },
            { question: "Ma'lumotlarni CPU, xotira va boshqa qurilmalar o'rtasida uzatishni ta'minlaydigan yo'llar qanday nomlanadi?", options: ["Shina tizimlari (Bus Systems) - Adreslar, Ma'lumotlar va Boshqaruv shinasi.", "Portlar (USB, HDMI, Ethernet kabi), Ma'lumotlar va Boshqaruv shinasi deb nomlanadi.", "Kesh xotira (L1, L2, L3) deb ataladi.", "Drayverlar (Driver) deb ataladi."], correctText: "Shina tizimlari (Bus Systems) - Adreslar, Ma'lumotlar va Boshqaruv shinasi." },
            { question: "Kiritish-chiqarish (I/O) qurilmalarining asosiy vazifasi nima?", options: ["Kompyuter va foydalanuvchi yoki boshqa qurilmalar o'rtasida aloqani ta'minlash.", "Faqat operatsion tizimni ishga tushirish jarayonini amalga oshirish.", "Faqat dasturlash tilida murakkab kod yozish jarayonini amalga oshirish.", "Elektr quvvatini kompyuterga taqsimlash, dasturlash tilida murakkab kod yozish jarayonini amalga oshirish."], correctText: "Kompyuter va foydalanuvchi yoki boshqa qurilmalar o'rtasida aloqani ta'minlash." },
            { question: "Operatsion tizim (OS) ning asosiy vazifasi nima?", options: ["Kompyuter resurslarini boshqarish va dasturlarni ishga tushirish uchun platforma yaratish.", "Faqat matnli hujjatlarni yaratish va ularni tahrirlash kabi jarayonlar.", "Faqat Internetga ulanishni ta'minlash.", "Apparat qismlarini ta'mirlash, dasturlash tilida murakkab kod yozish jarayonini amalga oshirish."], correctText: "Kompyuter resurslarini boshqarish va dasturlarni ishga tushirish uchun platforma yaratish." },
            { question: "Operatsion tizimlarning turlari qaysilar?", options: ["Bir foydalanuvchili, Ko'p foydalanuvchili, Bir vazifali, Ko'p vazifali, Tarmoq OS.", "Kiritish, Chiqarish, Qayta ishlash kabi asosiy vazifalari, Bir vazifali, Ko'p vazifali.", "Qattiq, Yumshoq, Suyuq kabi moddalarning holatlari, Bir vazifali, Ko'p vazifali.", "Simsiz, Simli, Optik kabi ulanish turlari."], correctText: "Bir foydalanuvchili, Ko'p foydalanuvchili, Bir vazifali, Ko'p vazifali, Tarmoq OS." },
            { question: "Windows operatsion tizimi qaysi turdagi manbaga (Source) ega?", options: ["Yopiq manbali (Closed-Source/Proprietary) litsenziyaga ega.", "Ochiq manbali (Open-Source) va qisman Yopiq manbali (Closed-Source/Proprietary) litsenziyaga ega.", "Gibrid manbali litsenziyaga ega.", "Faqat serverlar uchun maxsus mo'ljallangan."], correctText: "Yopiq manbali (Closed-Source/Proprietary) litsenziyaga ega." },
            { question: "Linux operatsion tizimi qaysi turdagi manbaga (Source) ega?", options: ["Ochiq manbali (Open-Source) litsenziyaga ega.", "Yopiq manbali (Closed-Source/Proprietary) litsenziyaga ega.", "Faqat ish stoli (Desktop) uchun maxsus mo'ljallangan.", "Faqat bir foydalanuvchili rejim uchun mo'ljallangan."], correctText: "Ochiq manbali (Open-Source) litsenziyaga ega." },
            { question: "Windows OSda tizimni tekshirish va nosozliklarni aniqlash uchun ishlatiladigan vosita nima?", options: ["Disk Check (CHKDSK) tizim yordam dasturi.", "ifconfig buyrug'i (ko'pincha Linuxda ishlatiladi).", "SSH mijozi dasturi.", "VLAN sozlamasi."], correctText: "Disk Check (CHKDSK) tizim yordam dasturi." },
            { question: "Linuxda fayl tizimidagi joylashuvni boshqarish va disk bo'shlig'ini optimallashtirish uchun qanday xizmat ko'rsatiladi?", options: ["Fayl tizimini tekshirish (fsck) va keraksiz fayllarni tozalash.", "Faqat apparat qismini yangi turiga almashtirish kabi jarayon.", "Faqat tarmoq kabelini uzish.", "Faqat protsessorning chastotasini oshirish (overclocking)."], correctText: "Fayl tizimini tekshirish (fsck) va keraksiz fayllarni tozalash." },
            { question: "Windowsda \"Drayverlarni yangilash\" qaysi vosita orqali amalga oshiriladi?", options: ["Qurilmalar menejeri (Device Manager) yordamida.", "Buyruq qatori (Command Prompt) yordamida.", "Registr muharriri (Registry Editor) yordamida.", "Disklarni bo'lish va viruslardan tozalash vositasi yordamida."], correctText: "Qurilmalar menejeri (Device Manager) yordamida." },
            { question: "Linuxda yangi dasturlarni o'rnatish va mavjudlarini yangilash uchun qaysi vosita (komanda) ishlatiladi?", options: ["apt, yum yoki dnf kabi paket menejerlari.", "ipconfig buyrug'I hamda Firewall konfiguratsiyasi.", "netstat vositasi.", "Firewall konfiguratsiyasi."], correctText: "apt, yum yoki dnf kabi paket menejerlari." },
            { question: "Operatsion tizimning \"Fayl tizimini boshqarish\" vazifasi nima?", options: ["Ma'lumotlarni qattiq diskda joylashtirish, tartiblash, kirishni boshqarish (masalan, NTFS, ext4).", "Elektr quvvatini tizim bo'ylab to'g'ri taqsimlash.", "Tarmoq protokollarini tanlash.", "Monitorning o'lchamini belgilash."], correctText: "Ma'lumotlarni qattiq diskda joylashtirish, tartiblash, kirishni boshqarish (masalan, NTFS, ext4)." },
            { question: "Kompyuter arxitekturasida \"Shina kengligi\" (Bus Width) nimani bildiradi?", options: ["Bir vaqtning o'zida uzatilishi mumkin bo'lgan bitlar soni.", "Kompyuter korpusining fizik o'lchamini va tarmoq kabelining uzunligini.", "Tarmoq kabelining uzunligini.", "Dasturlarning nomi."], correctText: "Bir vaqtning o'zida uzatilishi mumkin bo'lgan bitlar soni." },
            { question: "Operatsion tizim yadrosi (Kernel) ning asosiy roli nima?", options: ["Apparat qismlari va dasturlar o'rtasidagi asosiy aloqani ta'minlash, resurslarni taqsimlash.", "Foydalanuvchi interfeysini yaratish va uning vizual ko'rinishini boshqarish, ma'lumotlarni doimiy saqlash.", "Faqat ma'lumotlarni doimiy saqlash va ularni tartiblash.", "Faqat viruslarni aniqlash va ularni tizimdan butunlay o'chirish."], correctText: "Apparat qismlari va dasturlar o'rtasidagi asosiy aloqani ta'minlash, resurslarni taqsimlash." },
            { question: "Windowsda tizimni rezerv nusxalash (Backup) nima uchun kerak?", options: ["Apparat yoki dasturiy nosozlik yuz berganda ma'lumotlarni tiklash uchun.", "Kompyuterning haroratini past darajada ushlab turish uchun.", "Internet xavfsizligini kuchaytirish va viruslarga qarshi kurashish uchun.", "Qattiq disk bo'shlig'ini kamaytirish uchun."], correctText: "Apparat yoki dasturiy nosozlik yuz berganda ma'lumotlarni tiklash uchun." },
            { question: "Linuxda tizim ma'muriy buyruqlarini bajarish uchun qaysi foydalanuvchi (yoki buyruq) ishlatiladi?", options: ["Root (yoki sudo) super-foydalanuvchisi.", "Guest (Mehmon) foydalanuvchisi.", "User (Oddiy foydalanuvchi) nomi va Operator nomi.", "Operator nomi."], correctText: "Root (yoki sudo) super-foydalanuvchisi." },
            { question: "CPU ning tezligi qaysi birlikda o'lchanadi?", options: ["Gigasikl (GHz - Gigahertz).", "Bayt (Byte) va kilobayt (Kilobyte).", "Volt (V).", "Metr (m)."], correctText: "Gigasikl (GHz - Gigahertz)." },
            { question: "Operatsion tizimni yangilash (OS Update) ning xizmat ko'rsatishdagi ahamiyati nima?", options: ["Xavfsizlik kamchiliklarini bartaraf etish, yangi funksiyalarni qo'shish va barqarorlikni oshirish.", "Kompyuterning fizik qismlarini almashtirish va ularning to'g'ri ulanganligini tekshirish, viruslardan tozalash.", "Faqat fon rasmini o'zgartirish.", "Faqat internet provayderini almashtirish."], correctText: "Xavfsizlik kamchiliklarini bartaraf etish, yangi funksiyalarni qo'shish va barqarorlikni oshirish." },
            { question: "Windowsda diskni defragmentatsiya qilish nima uchun muhim?", options: ["Qattiq diskda (HDD) tarqoq ma'lumot bloklarini birlashtirib, o'qish/yozish tezligini oshirish uchun.", "Operativ xotira (RAM) hajmini ko'paytirish va tizim ishini tezlashtirish, viruslardan tozalash uchun.", "Viruslarni yo'qotish uchun.", "Monitor ekranini sozlash uchun."], correctText: "Qattiq diskda (HDD) tarqoq ma'lumot bloklarini birlashtirib, o'qish/yozish tezligini oshirish uchun." },
            { question: "Virtual xotira (Virtual Memory) tushunchasi nimani anglatadi?", options: ["Operativ xotira (RAM) yetarli bo'lmaganda, qattiq diskning bir qismini RAM vazifasida ishlatish.", "Faqat serverlarda ishlatiladigan xotira.", "Faqat o'yinlar uchun mo'ljallangan maxsus xotira va u qattiq diskning yarmini RAM vazifasida ishlatish.", "Faqat simsiz ulanishda ishlatiladigan xotira."], correctText: "Operativ xotira (RAM) yetarli bo'lmaganda, qattiq diskning bir qismini RAM vazifasida ishlatish." },
            { question: "BIOS/UEFI xizmat ko'rsatishda qanday rol o'ynaydi?", options: ["Kompyuterni ishga tushirish tartibini (boot order), apparat qismlarining parametrlari va xavfsizlikni sozlash imkonini beradi.", "Dasturlarni o'rnatish uchun xizmat qiladi va apparat qismlarining parametrlari va xavfsizlikni sozlash imkonini beradi..", "Tarmoq topologiyasini yaratish, internetni ta’minlash, protokollarni aniqlash, hamda kompyuterni ishga tushirish tartibini belgilash.", "Qattiq diskni tozalash."], correctText: "Kompyuterni ishga tushirish tartibini (boot order), apparat qismlarining parametrlari va xavfsizlikni sozlash imkonini beradi." },
            { question: "Plug and Play (Ula va Ishla) funksiyasining maqsadi nima?", options: ["Yangi qurilmani ulagandan so'ng, operatsion tizimning uni avtomatik tanishi va sozlashini ta'minlash.", "Faqat klaviaturani ulash.", "Internet tarmog’iga ulangandan so'ng, operatsion tizimning kompyuterlarni avtomatik tanishi va sozlashini ta'minlash.", "WiFi tarmog’iga ulangandan so'ng, operatsion tizimning kompyuterlarni avtomatik tanishi va sozlashini ta'minlash."], correctText: "Yangi qurilmani ulagandan so'ng, operatsion tizimning uni avtomatik tanishi va sozlashini ta'minlash." },
            { question: "Operatsion tizimda \"Xatolar jurnalini tekshirish\" (Event Log) nima uchun kerak?", options: ["Tizim va dasturlarda yuzaga kelgan nosozliklar, ogohlantirishlar va muhim hodisalar haqida ma'lumot olish uchun.", "Foydalanuvchi kirgan va tizimdan chiqqan vaqtni aniqlash.", "Internet tezligini o'lchash, tarmoqda yuzaga kelgan nosozliklar va muhim hodisalar haqida ma'lumot olish uchun uchun.", "Faqat qattiq diskning hajmini ko'rish, operatsion tizimning kompyuterlarni avtomatik tanishi uchun."], correctText: "Tizim va dasturlarda yuzaga kelgan nosozliklar, ogohlantirishlar va muhim hodisalar haqida ma'lumot olish uchun." },
            { question: "Kompyuter tarmog‘ining asosiy maqsadi nima?", options: ["Resurslarni umumiy ishlatish va foydalanuvchilar o'rtasida aloqani ta'minlash.", "Bitta kompyuterning ishlashini maksimal darajada tezlashtirish.", "Faqat bitta foydalanuvchiga xizmat ko'rsatish va boshqalarini navbatda ushlab turish.", "Matnli hujjatlar, audio va video fayllarni yaratish."], correctText: "Resurslarni umumiy ishlatish va foydalanuvchilar o'rtasida aloqani ta'minlash." },
            { question: "Tarmoqning geometrik joylashuvi va qurilmalarining o'zaro ulanish usuli nima deb ataladi?", options: ["Tarmoq topologiyasi.", "Tarmoq protokoli.", "Tarmoq manzili.", "Tarmoq kartasi."], correctText: "Tarmoq topologiyasi." },
            { question: "Eng keng tarqalgan tarmoq topologiyalari qaysilar?", options: ["Yulduz (Star), Shina (Bus), Halqa (Ring), Me'moriy (Mesh) turlari.", "Windows, Linux, MacOS kabi operatsion tizimlar.", "TCP, IP, HTTP kabi tarmoq protokollari va Shina (Bus), Halqa (Ring).", "Kesh, RAM, ROM kabi xotira turlari."], correctText: "Yulduz (Star), Shina (Bus), Halqa (Ring), Me'moriy (Mesh) turlari." },
            { question: "OSI modelining qancha qatlami (sathi) bor?", options: ["7 ta (Yetti).", "4 ta (To'rtta).", "5 ta (Beshda).", "3 ta (Uchta)."], correctText: "7 ta (Yetti)." },
            { question: "OSI modelining ma'lumotlarni elektr signallari orqali jismoniy uzatishni ta'minlovchi eng quyi qatlami (sathi) qaysi?", options: ["Fizik qatlam (Physical Layer).", "Tarmoq qatlami (Network Layer).", "Transport qatlami (Transport Layer).", "Amaliy qatlam (Application Layer)."], correctText: "Fizik qatlam (Physical Layer)." },
            { question: "OSI modelining IP (Internet Protocol) manzili bilan ishlaydigan qatlami qaysi?", options: ["Tarmoq qatlami (Network Layer).", "Ma'lumot kanal qatlami (Data Link Layer).", "Amaliy qatlam (Application Layer).", "Transport qatlami (Transport Layer)."], correctText: "Tarmoq qatlami (Network Layer)." },
            { question: "TCP/IP stekining nechta qatlami (sathi) mavjud?", options: ["4 ta (To'rtta) yoki 5 ta (OSI ga yaqinlashgan holda beshta).", "7 ta (Yetti) qatlami yoki 3 ta (OSI ga yaqinlashgan holda beshta).", "6 ta (Oltita) qatlami yoki 7 ta (OSI ga yaqinlashgan holda beshta).", "3 ta (Uchta) qatlami yoki 7 ta (OSI ga yaqinlashgan holda beshta)."], correctText: "4 ta (To'rtta) yoki 5 ta (OSI ga yaqinlashgan holda beshta)." },
            { question: "TCP (Transmission Control Protocol) ning asosiy vazifasi nima?", options: ["Ishonchli, ulanishga asoslangan ma'lumot uzatishni ta'minlash (xatolarni tekshirish va qayta yuborish).", "Tarmoqqa ulangan kompyuter manzilini aniqlash va u bilan xavfsiz aloqani o‘rnatish hamda ma’lumotlarni paketlash.", "Faqat elektron pochta xabarlarini uzatish, hamda ularni shifrlangan holda uzatishni ta'minlash yoki qayta yuborish.", "Faqat simsiz ulanishni ta'minlash."], correctText: "Ishonchli, ulanishga asoslangan ma'lumot uzatishni ta'minlash (xatolarni tekshirish va qayta yuborish)." },
            { question: "IP (Internet Protocol) ning asosiy vazifasi nima?", options: ["Ma'lumotlar paketini manbaidan manzilga yo'naltirish (routing) va IP address berish.", "Ma'lumotlarni faqat bitta kompyuter ichida saqlash, ularni saralash hamda xavfli viruslardan tozalash.", "Matnli hujjatlarni chop etish.", "Operatsion tizimni o'rnatish."], correctText: "Ma'lumotlar paketini manbaidan manzilga yo'naltirish (routing) va IP address berish." },
            { question: "Qaysi protokol ishonchsiz, ulanishsiz (Connectionless) ma'lumot uzatishni ta'minlaydi va tezlikka ustunlik beradi?", options: ["UDP (User Datagram Protocol).", "TCP (Transmission Control Protocol).", "HTTP (HyperText Transfer Protocol).", "FTP (File Transfer Protocol)."], correctText: "UDP (User Datagram Protocol)." },
            { question: "Veb-saytlarga kirish uchun ishlatiladigan asosiy protokol qaysi?", options: ["HTTP yoki HTTPS (Secure).", "SMTP (Simple Mail Transfer Protocol).", "POP3 (Post Office Protocol 3).", "DHCP (Dynamic Host Configuration Protocol)."], correctText: "HTTP yoki HTTPS (Secure)." },
            { question: "Fayllarni tarmoq orqali uzatish uchun ishlatiladigan protokol nima?", options: ["FTP (File Transfer Protocol).", "DNS (Domain Name System).", "ARP (Address Resolution Protocol).", "ICMP (Internet Control Message Protocol)."], correctText: "FTP (File Transfer Protocol)." },
            { question: "Tarmoqqa ulangan qurilmalarga IP manzilni avtomatik ravishda taqsimlaydigan xizmat (protokol) qaysi?", options: ["DHCP (Dynamic Host Configuration Protocol).", "SMTP (Simple Mail Transfer Protocol).", "HTTP (HyperText Transfer Protocol).", "SNMP (Simple Network Management Protocol)."], correctText: "DHCP (Dynamic Host Configuration Protocol)." },
            { question: "Ping buyrug'i nima uchun ishlatiladi?", options: ["Tarmoqdagi ikki qurilma orasidagi ulanish mavjudligini va ma'lumot uzatish kechikishini (latency) tekshirish uchun.", "Tarmoq manzilini o'zgartirish uchun.", "Fayllarni uzatish uchun.", "Veb-saytni yaratish uchun."], correctText: "Tarmoqdagi ikki qurilma orasidagi ulanish mavjudligini va ma'lumot uzatish kechikishini (latency) tekshirish uchun." },
            { question: "DNS (Domain Name System) ning asosiy vazifasi nima?", options: ["Domen nomlarini IP manzillarga aylantirish.", "Ma'lumotlarni shifrlash va manzilga uzatish.", "Tarmoq qurilmalarini yig'ish va aloqani tekshirish.", "Operatsion tizimni yangilash."], correctText: "Domen nomlarini IP manzillarga aylantirish." },
            { question: "Mahalliy tarmoqda (LAN) nosozlik manbalariga nimalar kiradi?", options: ["Noto'g'ri ulangan yoki shikastlangan kabellar, noto'g'ri tarmoq konfiguratsiyasi, qurilma (Switch/Router) nosozligi.", "Faqat dasturlash tili xatosi va belgilarning noto’g’ri ishlatilishi.", "Kompyuter korpusining isishi, WiFi qurilmasining ishdan chiqishi, noto'g'ri tarmoq konfiguratsiyasi (IP, Subnet), qurilma nosozligi.", "Monitorning o'chib qolishi."], correctText: "Noto'g'ri ulangan yoki shikastlangan kabellar, noto'g'ri tarmoq konfiguratsiyasi, qurilma (Switch/Router) nosozligi." },
            { question: "Internetga ulanish nosozliklarining eng keng tarqalgan manbasi nima?", options: ["Provayder (ISP) tomonidan xizmat uzilishi yoki Modem/Routerning noto'g'ri sozlanishi.", "Klaviatura va sichqoncha ishdan chiqishi, operatsion tizimga viruslarning ta’sir etishi.", "Qattiq diskning ma'lumotlar bilan to'lib ketishi, operatsion tizimga viruslarning ta’sir etishi.", "Operativ xotiraning yetishmasligi, klaviatura va sichqoncha ishdan chiqishi."], correctText: "Provayder (ISP) tomonidan xizmat uzilishi yoki Modem/Routerning noto'g'ri sozlanishi." },
            { question: "OSI modelining Ma'lumot kanal qatlami da ishlatiladigan manzil turi qaysi?", options: ["MAC manzili.", "IP manzili.", "Port raqami (masalan 80).", "Domen nomi."], correctText: "MAC manzili." },
            { question: "Tarmoqdagi ma'lumotlarni uzatish tezligi qaysi birlikda o'lchanadi?", options: ["Bit sekundiga (bps - bits per second) yoki uning hosilalari (Mbps, Gbps).", "Gigahertz (GHz) yoki uning hosilalari (Mbps, Gbps).", "Volt (V).", "Amper (A)."], correctText: "Bit sekundiga (bps - bits per second) yoki uning hosilalari (Mbps, Gbps)." },
            { question: "Patch panel (ulash paneli) tarmoqda qanday vazifani bajaradi?", options: ["Ulanish kabellarini markaziy nuqtada tartiblash va tarmoq uskunalariga ulanishni soddalashtirish.", "Tarmoq ichidagi barcha ma'lumotlar trafigini xavfsizlik qoidalari asosida faqat filtrlash funksiyasini bajaradi.", "Kompyuterlarga, smartfonlarga va printerlarga avtomatik tarzda IP manzillarni taqsimlab beradi.", "Tarmoq orqali uzatilayotgan barcha kirish va chiqish ma'lumotlarini to'liq shifrlaydi."], correctText: "Ulanish kabellarini markaziy nuqtada tartiblash va tarmoq uskunalariga ulanishni soddalashtirish." },
            { question: "ARP (Address Resolution Protocol) nima uchun ishlatiladi?", options: ["IP manzilini berilgan qurilmaning MAC manziliga aylantirish uchun (bir xil LAN ichida).", "Tarmoqdan tashqaridagi qurilmalarga to'g'ridan-to'g'ri, xavfsiz va ishonchli ulanish jarayonini ta'minlash.", "Brauzer orqali xohlagan veb-saytga tezkor kirish va u yerdagi ma'lumotlarni qabul qilish.", "Butun dunyo bo'ylab har qanday manzilga xavfsiz elektron pochta xabarlarini uzatish."], correctText: "IP manzilini berilgan qurilmaning MAC manziliga aylantirish uchun (bir xil LAN ichida)." },
            { question: "Port raqamlari tarmoqda nima uchun kerak?", options: ["Bitta IP manzilli kompyuterda turli xizmatlarni (masalan, HTTP, FTP, DNS) farqlash uchun.", "Faqat kompyuterning jismoniy (fizik) joylashuvini, manzilini to'g'ri va aniq ravishda belgilash uchun.", "Faqat tarmoq kabelining turini aniqlash uchun.", "CPU ning samaradorligini va uning hisoblash tezligini yuqori darajaga oshirish uchun."], correctText: "Bitta IP manzilli kompyuterda turli xizmatlarni (masalan, HTTP, FTP, DNS) farqlash uchun." },
            { question: "Koaksial kabel, o'ramali juft kabel va optik tolali kabel qaysi qatlamda ishlatiladi?", options: ["Fizik qatlam (Physical Layer).", "Transport qatlami (Transport Layer).", "Amaliy qatlam (Application Layer).", "Taqdimot qatlami (Presentation Layer)."], correctText: "Fizik qatlam (Physical Layer)." },
            { question: "Tarmoqqa xizmat ko'rsatishda IP manzil konfliktini (to'qnashuvini) bartaraf etish uchun nima qilish kerak?", options: ["Har bir qurilmaga yagona IP manzil berilganligini tekshirish (DHCP xizmatini yoki statik manzilni sozlash).", "Faqat kompyuterning jismoniy (fizik) joylashuvini, manzilini to'g'ri va aniq ravishda belgilash uchun.", "Monitor kabelini almashtirish va tarmoq kabelining turini va uning ishlash standartini aniqlash uchun ishlatiladi.", "Dasturlarni yangilash."], correctText: "Har bir qurilmaga yagona IP manzil berilganligini tekshirish (DHCP xizmatini yoki statik manzilni sozlash)." },
            { question: "NAT (Network Address Translation) ning asosiy vazifasi nima?", options: ["Xususiy IP manzillarni ommaviy IP manzilga o'tkazish, tashqi tarmoq bilan aloqa qilish imkonini berish.", "tarmoq orqali uzatilayotgan barcha kirish va chiqish ma'lumotlarini maksimal darajada shifrlash.", "Faqat fayllarni birgalikda ishlatish va chiqish ma'lumotlarini maksimal darajada shifrlash.", "Faqat kompyuterni tezlashtirish."], correctText: "Xususiy IP manzillarni ommaviy IP manzilga o'tkazish, tashqi tarmoq bilan aloqa qilish imkonini berish." },
            { question: "Router (Yo‘riqchi) ning asosiy vazifasi nima?", options: ["Turli tarmoqlar o'rtasida ma'lumot paketlarini manziliga qarab eng yaxshi marshrut bo'yicha yo'naltirish.", "Faqat bitta lokal tarmoq (LAN) ichida barcha kompyuter va boshqa tarmoq qurilmalarini bir-biri bilan ulash.", "Faqat tarmoqqa ulangan har bir qurilmaga IP manzillarni avtomatik tarzda taqsimlab, ulashni boshqarish.", "Tarmoq orqali uzatilayotgan barcha kiruvchi va chiquvchi ma'lumotlarni shifrlash vazifasini bajarish."], correctText: "Turli tarmoqlar o'rtasida ma'lumot paketlarini manziliga qarab eng yaxshi marshrut bo'yicha yo'naltirish." },
            { question: "Switch (Kommutator) ning asosiy vazifasi nima?", options: ["Bir xil tarmoq (LAN) ichida ma'lumotlarni MAC manziliga qarab aniq portga uzatish (filtrlab).", "Turli xil tarmoqlar o'rtasida ma'lumot paketlarini manziliga qarab eng yaxshi yo'l bo'yicha yo'naltirish.", "Kompyuterlarga, smartfonlarga va printerlarga tezkor internetga ulanishni ishonchli ta'minlash.", "Foydalanuvchi parolini xavfsizlik talablari asosida o'zgartirish va xavfsizlikni kuchaytirish."], correctText: "Bir xil tarmoq (LAN) ichida ma'lumotlarni MAC manziliga qarab aniq portga uzatish (filtrlab)." },
            { question: "Routing protokollari nima uchun kerak?", options: ["Routerlar o'rtasida marshrutlash jadvallarini almashish va tarmoqdagi eng yaxshi yo'lni aniqlash uchun.", "Tarmoq orqali uzatilayotgan barcha kiruvchi va chiquvchi maxfiy ma'lumotlarni shifrlash vazifasini bajarish.", "Faqat bitta kompyuter ichida dasturlarni boshqarish.", "Saqlash qurilmalarida (HDD/SSD) ma'lumotlarni tartiblash uchun maxsus fayl tizimini yaratish."], correctText: "Routerlar o'rtasida marshrutlash jadvallarini almashish va tarmoqdagi eng yaxshi yo'lni aniqlash uchun." },
            { question: "RIP (Routing Information Protocol) qanday turdagi marshrutlash protokoliga kiradi?", options: ["Distant vektorli (Distance Vector) turiga kiradi.", "Havola holati (Link State) turiga kiradi.", "Manzilni aniqlash protokoli turiga kiradi.", "Amaliy qatlam protokoli turiga kiradi."], correctText: "Distant vektorli (Distance Vector) turiga kiradi." },
            { question: "OSPF (Open Shortest Path First) qanday turdagi marshrutlash protokoliga kiradi?", options: ["Havola holati (Link State) turiga kiradi.", "Distant vektorli (Distance Vector) turiga kiradi.", "Tashqi shlyuz protokoli turiga kiradi.", "Transport qatlami protokoli turiga kiradi."], correctText: "Havola holati (Link State) turiga kiradi." },
            { question: "BGP (Border Gateway Protocol) odatda qanday tarmoqlarda ishlatiladi?", options: ["Internetning avtonom tizimlari (AS) o'rtasida, ya'ni internet magistralida.", "Kichik uy tarmoqlarida.", "Faqat bitta xonadagi muayyan kompyuterlar orasida ya'ni mahalliy tarmoqda.", "Faqat printerlarni ulash uchun."], correctText: "Internetning avtonom tizimlari (AS) o'rtasida, ya'ni internet magistralida." },
            { question: "VLAN (Virtual Local Area Network) ning asosiy maqsadi nima?", options: ["Bitta Switch/Fizik tarmoqni mantiqiy jihatdan bir nechta alohida tarmoqlarga (Broadcast domenlariga) ajratish.", "Ikkita yoki undan ortiq turli xil tarmoqlarni (masalan, turli LANlarni) bir-biriga birlashtirish jarayoni.", "Internet tezligini oshirish, tarmoq uskunalarini o'zgartirish orqali Internetga ulanish tezligini sun'iy ravishda oshirish.", "Kompyuterga elektr toki yetkazib berish va uning barqaror quvvatlanishini ta'minlash.."], correctText: "Bitta Switch/Fizik tarmoqni mantiqiy jihatdan bir nechta alohida tarmoqlarga (Broadcast domenlariga) ajratish." },
            { question: "VLAN konfiguratsiyasi nima uchun tarmoq xavfsizligini oshiradi?", options: ["Har xil VLAN dagi trafikni bir-biridan ajratadi, shu bilan bir tarmoqdagi xato yoki hujum boshqa tarmoqqa tarqalishini cheklaydi.", "Faqat tarmoqqa ulangan yangi qurilmalarga IP manzilni avtomatik ravishda taqsimlab, ishlashini ta'minlaydi.", "Faqat tarmoq kabelining tashqi shikastlanishdan va har qanday fizik va boshqa ta'sirlardan ishonchli himoya qilinishini to’liq kafolatlaydi.", "Faqat kompyuterning Markaziy Protsessorining (CPU) ishlash chastotasini boshqaradi va uning yuklanishini nazorat qiladi."], correctText: "Har xil VLAN dagi trafikni bir-biridan ajratadi, shu bilan bir tarmoqdagi xato yoki hujum boshqa tarmoqqa tarqalishini cheklaydi." },
            { question: "Firewall (Devor) ning asosiy vazifasi nima?", options: ["Tarmoq trafigini oldindan belgilangan qoidalar asosida filtrlash, ruxsat etilmagan kirish/chiqishni bloklash.", "Faqat tarmoqdagi barcha ma'lumotlarni shifrlash va ularning butunligini kriptografik usullar bilan ta'minlash.", "Faqat operatsion tizimga yangi amaliy dasturlarni o'rnatish va ularning konfiguratsiyasini sozlash.", "Faqat kompyuterning fizik xavfsizligini ta'minlash."], correctText: "Tarmoq trafigini oldindan belgilangan qoidalar asosida filtrlash, ruxsat etilmagan kirish/chiqishni bloklash." },
            { question: "Firewall turlari qaysilar?", options: ["Paket filtrlaydigan, Davlatli (Stateful Inspection), Proksi-server (Proxy), Dasturiy va Apparatli turlari.", "Tarmoqqa ulanishni ta'minlaydigan Simli, Simsiz, Optik ulanish texnologiyalari va ularning asosiy turlari.", "Tarmoq uskunalarining fizik o'lchovlariga qarab Kichik, O'rta, Katta hajm turlari.", "Qattiq, Yumshoq, Suyuq holat turlari."], correctText: "Paket filtrlaydigan, Davlatli (Stateful Inspection), Proksi-server (Proxy), Dasturiy va Apparatli turlari." },
            { question: "IDS (Intrusion Detection System) nima?", options: ["Tarmoq trafigini va tizim faoliyatini nazorat qilib, xavfsizlikka oid shubhali yoki zararli harakatlarni aniqlovchi tizim.", "Faqat kompyuter tizimidagi barcha turdagi viruslarni topib, ularni butunlay o'chiruvchi dastur.", "Faqat tarmoqqa ulangan barcha qurilmalarga IP manzillarni avtomatik tarzda taqsimlovchi qurilma va ularni saqlash uchun arxivlovchi vosita.", "Faqat fayllarni arxivlovchi vosita."], correctText: "Tarmoq trafigini va tizim faoliyatini nazorat qilib, xavfsizlikka oid shubhali yoki zararli harakatlarni aniqlovchi tizim." },
            { question: "IPS (Intrusion Prevention System) ning IDS dan farqi nima?", options: ["IPS shubhali harakatlarni aniqlabgina qolmay, balki ularni avtomatik ravishda bloklaydi yoki bartaraf etadi.", "IDS faqat tarmoq orqali uzatilayotgan barcha ma'lumotlarni shifrlaydi va ularning butunligini ta'minlaydi.", "IPS faqat kompyuterning tashqi tarmoqqa (Internetga) uzluksiz va yuqori tezlikda ulanishini ta'minlaydi.", "IDS faqat tarmoqdagi barcha turdagi routerlarda ishlaydi va kommutatorlarda (switchlarda) ishlay olmaydi."], correctText: "IPS shubhali harakatlarni aniqlabgina qolmay, balki ularni avtomatik ravishda bloklaydi yoki bartaraf etadi." },
            { question: "Tarmoq xavfsizligini ta'minlashning asosiy uch tamoyili (CIA) nima?", options: ["Maxfiylik (Confidentiality), Butunlik (Integrity), Mavjudlik (Availability) tamoyillari.", "Tarmoq trafigini boshqarishning uch asosiy usuli: Kommutatsiya, Marshrutlash, Filtrlash.", "Kompyuter tizimlariga xizmat ko'rsatishning muhim bosqichlari: O'rnatish, Sozlash, Yangilash.", "Tarmoqning asosiy qurilmalari: Turli xil Kabellar, Kommutatorlar (Switchlar) va Yo'riqchilar (Routerlar)."], correctText: "Maxfiylik (Confidentiality), Butunlik (Integrity), Mavjudlik (Availability) tamoyillari." },
            { question: "Tarmoq xavfsizligida Shifrlash (Encryption) qaysi tamoyilni ta'minlaydi?", options: ["Maxfiylik (Confidentiality).", "Butunlik (Integrity).", "Mavjudlik (Availability).", "Shlyuzlik."], correctText: "Maxfiylik (Confidentiality)." },
            { question: "Kriptografik xeshlash (Cryptographic Hashing) qaysi tamoyilni ta'minlaydi?", options: ["Butunlik (Integrity).", "Maxfiylik (Confidentiality).", "Mavjudlik (Availability).", "Shlyuzlik."], correctText: "Butunlik (Integrity)." },
            { question: "Tarmoq xizmatida \"Port Scanning\" (Portlarni skanerlash) nima uchun ishlatiladi?", options: ["Tarmoqdagi qurilmalarda qaysi xizmatlarning faol va ochiq ekanligini (xavfsizlik uchun) aniqlash uchun.", "Tarmoq uskunalarini o'zgartirish orqali Internetga ulanish tezligini sun'iy ravishda yuqori darajada oshirish uchun.", "Kompyuterning asosiy komponentlari (CPU, GPU) haroratini doimiy ravishda o'lchash va nazorat qilish uchun.", "Operatsion tizimni o'rnatish uchun."], correctText: "Tarmoqdagi qurilmalarda qaysi xizmatlarning faol va ochiq ekanligini (xavfsizlik uchun) aniqlash uchun." },
            { question: "Routerda \"ACL\" (Access Control List) nima?", options: ["Tarmoq trafigini ruxsat berish yoki bloklash uchun ishlatiladigan qoidalar to'plami.", "Faqat tarmoqda ishlatiladigan turli kabel turlarini va ularning texnik parametrlarini aniqlovchi ro'yxat.", "Faqat IP manzillarni o'zgartiruvchi ro'yxat.", "Faqat foydalanuvchi parollarini saqlovchi ro'yxat."], correctText: "Tarmoq trafigini ruxsat berish yoki bloklash uchun ishlatiladigan qoidalar to'plami." },
            { question: "VPN (Virtual Private Network) ning asosiy maqsadi nima?", options: ["Ommaviy tarmoq (masalan, Internet) orqali xavfsiz, shifrlangan shaxsiy aloqani yaratish.", "Faqat lokal tarmoq (LAN) ichidagi ma'lumotlar uzatish tezligini sun'iy ravishda yuqori darajada oshirish.", "Kompyuterning barcha fizik qismlarini (hardware) ishini to'g'ri boshqarish va nazorat qilish.", "Faqat dasturlarni yangilash."], correctText: "Ommaviy tarmoq (masalan, Internet) orqali xavfsiz, shifrlangan shaxsiy aloqani yaratish." },
            { question: "Switch qurilmasi qaysi OSI qatlamida ishlaydi?", options: ["Ma'lumot kanal qatlami (Data Link Layer - 2-qatlam).", "Tarmoq qatlami (Network Layer - 3-qatlam).", "Fizik qatlam (Physical Layer - 1-qatlam).", "Amaliy qatlam (Application Layer - 7-qatlam)."], correctText: "Ma'lumot kanal qatlami (Data Link Layer - 2-qatlam)." },
            { question: "Router qurilmasi qaysi OSI qatlamida ishlaydi?", options: ["Tarmoq qatlami (Network Layer - 3-qatlam).", "Ma'lumot kanal qatlami (Data Link Layer - 2-qatlam).", "Fizik qatlam (Physical Layer - 1-qatlam).", "Amaliy qatlam (Application Layer - 7-qatlam)."], correctText: "Tarmoq qatlami (Network Layer - 3-qatlam)." },
            { question: "Tarmoq xavfsizligida Brute-Force hujumi nima?", options: ["Tizimga kirish uchun parollarni tizimli ravishda barcha mumkin bo'lgan kombinatsiyalarni sinab ko'rish orqali topishga urinish.", "Qurilmaning tarmoqqa ulanishini butunlay to'xtatish maqsadida, asosiy tarmoq kabelini uzish.", "Faqat kompyuter tizimida saqlanayotgan barcha shaxsiy ma'lumotlarni butunlay o'chirish.", "Faqat tarmoqqa ulangan qurilmaning IP manzilini tizimli ravishda boshqa bir manzilga o'zgartirish, asosiy tarmoq kabelini uzish."], correctText: "Tizimga kirish uchun parollarni tizimli ravishda barcha mumkin bo'lgan kombinatsiyalarni sinab ko'rish orqali topishga urinish." },
            { question: "MAC manzilini filtrlaydigan (MAC Filtering) xavfsizlik mexanizmi qayerda qo'llaniladi?", options: ["Switch va Access Point (Kirish nuqtasi) qurilmalarida.", "Faqat dasturlash muhitida.", "Faqat CPU ichida.", "Faqat monitor kabelida."], correctText: "Switch va Access Point (Kirish nuqtasi) qurilmalarida." },
            { question: "DoS (Denial of Service) hujumining maqsadi nima?", options: ["Tarmoq resursini yoki xizmatini qonuniy foydalanuvchilar uchun mavjud bo'lmay qolishiga erishish.", "Faqat tarmoqdan maxfiy va shaxsiy ma'lumotlarni noqonuniy yo'llar bilan o'g'irlash harakatini amalga oshirish.", "Faqat kompyuterning fizik qismlarini almashtirish.", "Faqat kompyuterga o'rnatilgan operatsion tizimni xavfsizlik maqsadida yangi versiyaga muntazam yangilash."], correctText: "Tarmoq resursini yoki xizmatini qonuniy foydalanuvchilar uchun mavjud bo'lmay qolishiga erishish." },
            { question: "Qaysi routing protokoli uzoq masofali (Inter-Domain) marshrutlash uchun mo'ljallangan?", options: ["BGP (Border Gateway Protocol).", "RIP (Routing Information Protocol).", "OSPF (Open Shortest Path First).", "EIGRP (Enhanced Interior Gateway Routing Protocol)."], correctText: "BGP (Border Gateway Protocol)." },
            { question: "Tarmoqni boshqarish va monitoring qilish uchun qaysi protokol keng qo'llaniladi?", options: ["SNMP", "SSH", "Telnet", "ARP"], correctText: "SNMP" }
        ];



// LOGIKA
let currentQuestions = [];
let currentQuizIndex = 0;
let score = 0;
let isClickable = true;

// Elementlar
const welcomeScreen = document.getElementById('welcome-screen');
const quizApp = document.getElementById('quiz-app');
const resultScreen = document.getElementById('result-screen');
const questionEl = document.getElementById('question-text');
const optionsList = document.getElementById('options-list');
const currentStatusEl = document.getElementById('current-status');
const scoreStatusEl = document.getElementById('score-status');
const progressBar = document.getElementById('progress-bar');
const modeNameEl = document.getElementById('mode-name');

function startMode(mode) {
    welcomeScreen.style.display = 'none';
    quizApp.style.display = 'block';
    
    if (mode === 'practice') {
        currentQuestions = [...allQuestionsData]; 
        modeNameEl.innerText = "Takrorlash";
    } else {
        // 30 talik Random Imtihon
        const shuffled = [...allQuestionsData].sort(() => 0.5 - Math.random());
        currentQuestions = shuffled.slice(0, 30);
        modeNameEl.innerText = "Imtihon (30)";
    }

    currentQuizIndex = 0;
    score = 0;
    loadQuestion();
}

function loadQuestion() {
    isClickable = true;
    optionsList.innerHTML = '';
    
    const currentData = currentQuestions[currentQuizIndex];
    
    // Savol matni
    questionEl.innerText = `${currentQuizIndex + 1}. ${currentData.question}`;
    
    // Progress
    const progressPercent = ((currentQuizIndex) / currentQuestions.length) * 100;
    progressBar.style.width = `${progressPercent}%`;
    currentStatusEl.innerText = `${currentQuizIndex + 1} / ${currentQuestions.length}`;
    scoreStatusEl.innerText = `${score} to'g'ri`;

    // Variantlarni aralashtirish
    let shuffledOptions = [...currentData.options].sort(() => 0.5 - Math.random());
    const correctText = currentData.correctText;

    shuffledOptions.forEach(opt => {
        const btn = document.createElement('button');
        btn.innerText = opt;
        btn.classList.add('option-btn');
        btn.onclick = () => checkAnswer(opt, correctText, btn);
        optionsList.appendChild(btn);
    });
}

function checkAnswer(selected, correct, btnElement) {
    if (!isClickable) return;
    isClickable = false; // Ketma-ket bosishni oldini olish

    const buttons = document.querySelectorAll('.option-btn');
    
    if (selected === correct) {
        btnElement.classList.add('correct');
        score++;
    } else {
        btnElement.classList.add('wrong');
        // To'g'risini ko'rsatamiz
        buttons.forEach(b => {
            if (b.innerText === correct) b.classList.add('correct');
        });
    }

    scoreStatusEl.innerText = `${score} to'g'ri`;

    // 1.2 sekunddan keyin keyingisiga o'tish
    setTimeout(() => {
        currentQuizIndex++;
        if (currentQuizIndex < currentQuestions.length) {
            loadQuestion();
        } else {
            showResults();
        }
    }, 1200);
}

function showResults() {
    quizApp.style.display = 'none';
    resultScreen.style.display = 'flex';
    
    const total = currentQuestions.length;
    const percentage = (score / total) * 100;
    
    document.getElementById('total-count').innerText = `/ ${total}`;
    document.getElementById('final-score').innerText = score;
    
    const msgEl = document.getElementById('result-message');
    if (percentage >= 80) msgEl.innerText = "Ajoyib natija! 🎉";
    else if (percentage >= 60) msgEl.innerText = "Yaxshi, lekin yana o'qing. 📚";
    else msgEl.innerText = "Qayta urinib ko'ring. 💪";
}